apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-k8s
resources:
  - ../../base/api
  - ../../base/web
  - ../../base/db
configMapGenerator:
  - behavior: replace
    envs:
      - .api.env
    name: api
